//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdleMiner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdleMiner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Settings.
        /// </summary>
        internal static string Activity_Settings {
            get {
                return ResourceManager.GetString("Activity_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdleMiner.
        /// </summary>
        internal static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin mining when computer has been idle for:.
        /// </summary>
        internal static string Begin_Mining_When_Label {
            get {
                return ResourceManager.GetString("Begin_Mining_When_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brought to you by JonnyFunFun.
        /// </summary>
        internal static string Brought_To_You_By {
            get {
                return ResourceManager.GetString("Brought_To_You_By", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon C21 {
            get {
                object obj = ResourceManager.GetObject("C21", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit_Label {
            get {
                return ResourceManager.GetString("Exit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid URL!.
        /// </summary>
        internal static string Invalid_URL_Message {
            get {
                return ResourceManager.GetString("Invalid_URL_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string Invalid_URL_Title {
            get {
                return ResourceManager.GetString("Invalid_URL_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miner Settings.
        /// </summary>
        internal static string Miner_Settings_Label {
            get {
                return ResourceManager.GetString("Miner_Settings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdleMiner has been minimized to the tray.  To exit, right click the icon.  To open the settings window, double click it. Click this balloon to hide this message forever..
        /// </summary>
        internal static string Minimized_Balloon_Text {
            get {
                return ResourceManager.GetString("Minimized_Balloon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdleMiner Minimized.
        /// </summary>
        internal static string Minimized_Balloon_Title {
            get {
                return ResourceManager.GetString("Minimized_Balloon_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon mining {
            get {
                object obj = ResourceManager.GetObject("mining", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenCL Device:.
        /// </summary>
        internal static string OpenCL_Device_Label {
            get {
                return ResourceManager.GetString("OpenCL_Device_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading devices available to poclbm:
        ///{0}.
        /// </summary>
        internal static string Poclbm_Device_Loading_Error_Message {
            get {
                return ResourceManager.GetString("Poclbm_Device_Loading_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poclbm Error.
        /// </summary>
        internal static string Poclbm_Error_Title {
            get {
                return ResourceManager.GetString("Poclbm_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poclbm is taking longer than expected to give me a list of devices.  Would you like to continue waiting?.
        /// </summary>
        internal static string Poclbm_Is_Being_Slow_Message {
            get {
                return ResourceManager.GetString("Poclbm_Is_Being_Slow_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue waiting?.
        /// </summary>
        internal static string Poclbm_Is_Being_Slow_Title {
            get {
                return ResourceManager.GetString("Poclbm_Is_Being_Slow_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Running {
            get {
                object obj = ResourceManager.GetObject("Running", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings from registry
        ///{0}
        ///Defaults will be loaded instead..
        /// </summary>
        internal static string Settings_Loading_Error_Message {
            get {
                return ResourceManager.GetString("Settings_Loading_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Settings.
        /// </summary>
        internal static string Settings_Loading_Error_Title {
            get {
                return ResourceManager.GetString("Settings_Loading_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find poclbm.exe! Please check to ensure that the poclbm miner exists in the same path as IdleMiner!.
        /// </summary>
        internal static string Unable_To_Find_poclbm_Message {
            get {
                return ResourceManager.GetString("Unable_To_Find_poclbm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find miner.
        /// </summary>
        internal static string Unable_To_Find_poclbm_Title {
            get {
                return ResourceManager.GetString("Unable_To_Find_poclbm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse that timespan.  Please try a delay such as:
        ///1 day 2 hours 10 minutes 30 seconds.
        /// </summary>
        internal static string Unable_To_Parse_Time_Message {
            get {
                return ResourceManager.GetString("Unable_To_Parse_Time_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time.
        /// </summary>
        internal static string Unable_To_Parse_Time_Title {
            get {
                return ResourceManager.GetString("Unable_To_Parse_Time_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use vectors?.
        /// </summary>
        internal static string Use_Vectors_Label {
            get {
                return ResourceManager.GetString("Use_Vectors_Label", resourceCulture);
            }
        }
    }
}
